language: csharp
solution: Insight.Autofac.Extensions.MediatR.sln
mono: none
dotnet: 3.1.101
stages:
 - build
 - publish
jobs:
 include:
  - stage: build
    name: build solution
    script: dotnet restore && dotnet build
  - stage: publish
    name: publish nuget package
    if: tag IS presented
    script: ./publish-nuget.sh "$NUGET_SOURCE" "$NUGET_KEY" "$TRAVIS_TAG"
